name: Run Static Code Analysis

on: 
  pull_request:
    branches:
      - dev

jobs:
  Run_Analysis:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.1"
      - name: flake8 Lint
        uses: py-actions/flake8@v2
